version: '3.4'

services:
  food.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6001:80"
    volumes:
      - /data/files/upload/product:/var/product
      - /data/files/upload/slider:/var/slider
  fooddb:
    container_name: fooddb
    environment:
       - POSTGRES_USER=admin
       - POSTGRES_PASSWORD=admin1234
    restart: always
    ports:
      - "5436:5432"
    volumes:
      - /data/db:/var/lib/postgresql/data2/